# Generated by Django 6.0.2 on 2026-03-08 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSSSRemake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='courses',
            field=models.ManyToManyField(to='BSSSRemake.course'),
        ),
        migrations.DeleteModel(
            name='schoolCourses',
        ),
    ]
