# Generated by Django 6.0.2 on 2026-03-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSSSRemake', '0002_school_courses_delete_schoolcourses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='achievementStandards',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='school',
            name='courses',
            field=models.ManyToManyField(blank=True, to='BSSSRemake.course'),
        ),
    ]
