# Generated by Django 6.0.2 on 2026-03-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSSSRemake', '0003_rename_achievementstandards_course_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['name'], name='courseIndex'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['name'], name='schoolIndex'),
        ),
    ]
