# Generated by Django 6.0.2 on 2026-03-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSSSRemake', '0004_alter_course_name_alter_school_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='course',
            name='courseIndex',
        ),
        migrations.RemoveIndex(
            model_name='school',
            name='schoolIndex',
        ),
        migrations.AddField(
            model_name='course',
            name='semester1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='unitInformation',
            field=models.CharField(db_index=True, default='Unknown', max_length=50),
        ),
    ]
