# Generated by Django 6.0.2 on 2026-03-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSSSRemake', '0005_remove_course_courseindex_remove_school_schoolindex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='room',
            field=models.CharField(default='Unknown', max_length=15),
        ),
    ]
