# Generated by Django 6.0.2 on 2026-03-11 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BSSSRemake', '0006_course_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='room',
        ),
    ]
