# Generated by Django 6.0.2 on 2026-04-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSSSRemake', '0007_remove_course_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weighting', models.IntegerField(db_index=True)),
                ('project', models.CharField(choices=[('RES', 'Research'), ('PRO', 'Prototype'), ('FIN', 'Final Build'), ('REF', 'Reflection')], max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='semester1',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
