# Generated by Django 6.0.2 on 2026-04-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSSSRemake', '0008_projectinfo_alter_course_semester1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='project',
            field=models.CharField(choices=[('RESEARCH', 'RESEARCH'), ('PROTOTYPE', 'PROTOTYPE'), ('FINAL_BUILD', 'FINAL_BUILD'), ('REFLECTION', 'REFLECTION')], max_length=20),
        ),
    ]
