# Generated by Django 6.0.2 on 2026-04-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSSSRemake', '0009_alter_projectinfo_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='courseName',
            field=models.CharField(choices=[('SOFTWARE', 'SOFTWARE'), ('PHYSICS', 'PHYSICS'), ('MATHS', 'MATHS'), ('ROBOTICS', 'ROBOTICS')], default='SOFTWARE', max_length=20),
        ),
    ]
