# Generated by Django 6.0.2 on 2026-04-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSSSRemake', '0010_projectinfo_coursename'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='createdAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
