# Generated by Django 6.0.2 on 2026-04-27 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BSSSRemake', '0011_projectinfo_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinfo',
            name='weighting',
        ),
    ]
